name: Ubuntu Desktop Virtual Machine
on: 
  workflow_dispatch:
   inputs:
      crdauthcode:
        description: 'Enter ChromeRemoteDesktop Headless code'
        required: true
      pincode:
        description: 'Six digit Pin'
        required: true
defaults:
  run:
    shell: bash
    
jobs:
  build:
    name: Linux System Build
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
 ##   - name: If failed, means ok
 ##     run: ./not-exist-file.sh it bloke build
    - name: Setting Up the Ubuntu Environment
    ##  if: ${{ failure() }}
      run: bash linux-desktop.sh
      env:
        LINUX_USER_PASSWORD: ${{ secrets.LINUX_USER_PASSWORD }}
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
        CHROME_HEADLESS_CODE: ${{ github.event.inputs.crdauthcode }}
        LINUX_MACHINE_NAME: ${{ secrets.LINUX_MACHINE_NAME }}
        LINUX_USERNAME: ${{ secrets.LINUX_USERNAME }}
        GOOGLE_REMOTE_PIN: ${{ github.event.inputs.pincode }}
    - name: Keep Running Ubuntu System and keepAlive
    ##  if: ${{ failure() }}
      run: sleep 6h
